CREATE TABLE AIRLINE(
    AIRLINE_ID INT PRIMARY KEY,
    AIRLINE_NAME VARCHAR(100) NOT NULL
);

CREATE TABLE USER(
    USERNAME VARCHAR(50) PRIMARY KEY,
    F_NAME VARCHAR(50),
    M_NAME VARCHAR(50),
    L_NAME VARCHAR(50),
    DOB DATE,
    AGE INT,
    GENDER VARCHAR(10),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    PIN_CODE VARCHAR(10)
);

CREATE TABLE USER_PHONE(
    USERNAME VARCHAR(50),
    PHONE_NO VARCHAR(15),
    PRIMARY KEY(USERNAME, PHONE_NO),
    FOREIGN KEY(USERNAME) REFERENCES USER(USERNAME)
);

CREATE TABLE FLIGHT(
    FLIGHT_NO INT PRIMARY KEY,
    FLIGHT_NAME VARCHAR(100),
    SOURCE VARCHAR(50),
    DESTINATION VARCHAR(50),
    DEP_TIME TIME,
    ARR_TIME TIME,
    DISTANCE INT,
    SEAT_AVL INT,
    AIRLINE_ID INT,
    FOREIGN KEY (AIRLINE_ID) REFERENCES AIRLINE(AIRLINE_ID)
);

CREATE TABLE CLASS(
    CLASS_ID INT PRIMARY KEY,
    CLASS_TYPE VARCHAR(30),
    FARE DECIMAL(10,2),
    FLIGHT_NO INT,
    FOREIGN KEY (FLIGHT_NO) REFERENCES FLIGHT(FLIGHT_NO)
);

CREATE TABLE TICKET(
    PNR_NO INT PRIMARY KEY,
    USERNAME VARCHAR(50),
    FLIGHT_NO INT,
    SEAT_NO VARCHAR(10),
    PASSENGER_NAME VARCHAR(100),
    SOURCE VARCHAR(50),
    DESTINATION VARCHAR(50),
    DATE_TIME DATETIME,
    FOREIGN KEY(USERNAME) REFERENCES USER(USERNAME),
    FOREIGN KEY(FLIGHT_NO) REFERENCES FLIGHT(FLIGHT_NO)
);

CREATE TABLE PAYMENT(
    TRANSACTION_ID INT PRIMARY KEY,
    PNR_NO INT UNIQUE,
    PAYMENT_MODE VARCHAR(30),
    AMOUNT DECIMAL(10,2),
    FOREIGN KEY(PNR_NO) REFERENCES TICKET(PNR_NO)
);

CREATE TABLE CANCELLATION(
    CANCEL_ID INT PRIMARY KEY,
    USERNAME VARCHAR(50),
    PNR_NO INT,
    CANCEL_DATE DATETIME,
    FOREIGN KEY(USERNAME) REFERENCES USER(USERNAME),
    FOREIGN KEY(PNR_NO) REFERENCES TICKET(PNR_NO)
);

CREATE TABLE PASSENGER(
    PASSENGER_ID INT PRIMARY KEY,
    PNR_NO INT,
    NAME VARCHAR(100),
    AGE INT,
    GENDER VARCHAR(10),
    FOREIGN KEY(PNR_NO) REFERENCES TICKET(PNR_NO)
);
