USE airline_db;
SELECT * FROM USERS;

SELECT * FROM FLIGHT;

SELECT * 
FROM FLIGHT
WHERE SOURCE = 'Delhi' AND DESTINATION = 'Mumbai';

SELECT * 
FROM TICKET
WHERE USER_ID = 1;

SELECT * FROM PAYMENT;

SELECT F.FLIGHT_NO, F.SOURCE, F.DESTINATION, A.AIRLINE_NAME
FROM FLIGHT F
JOIN AIRLINE A ON F.AIRLINE_ID = A.AIRLINE_ID;

SELECT T.PNR_NO, U.F_NAME, U.L_NAME, T.SEAT_NO
FROM TICKET T
JOIN USERS U ON T.USER_ID = U.USER_ID;

SELECT T.PNR_NO, C.CLASS_TYPE, T.SEAT_NO
FROM TICKET T
JOIN CLASS C ON T.CLASS_ID = C.CLASS_ID;

SELECT 
    U.F_NAME,
    F.FLIGHT_NO,
    F.SOURCE,
    F.DESTINATION,
    C.CLASS_TYPE,
    T.SEAT_NO,
    P.AMOUNT
FROM TICKET T
JOIN USERS U ON T.USER_ID = U.USER_ID
JOIN FLIGHT F ON T.FLIGHT_NO = F.FLIGHT_NO
JOIN CLASS C ON T.CLASS_ID = C.CLASS_ID
JOIN PAYMENT P ON T.PNR_NO = P.PNR_NO;

SELECT COUNT(*) AS TOTAL_TICKETS
FROM TICKET;

SELECT SUM(AMOUNT) AS TOTAL_REVENUE
FROM PAYMENT;

SELECT FLIGHT_NO, COUNT(*) AS TOTAL_TICKETS
FROM TICKET
GROUP BY FLIGHT_NO

SELECT USER_ID, COUNT(*) AS BOOKINGS
FROM TICKET
GROUP BY USER_ID
HAVING COUNT(*) > 1;

SELECT * 
FROM FLIGHT
WHERE FLIGHT_NO NOT IN (
    SELECT FLIGHT_NO FROM TICKET
);

SELECT *
FROM PAYMENT
WHERE AMOUNT = (
    SELECT MAX(AMOUNT) FROM PAYMENT
);

