CREATE DATABASE airline_db;
USE airline_db;

CREATE TABLE AIRLINE(
    AIRLINE_ID INT PRIMARY KEY,
    AIRLINE_NAME VARCHAR(100) NOT NULL
);

CREATE TABLE USERS(
    USER_ID INT PRIMARY KEY,
    F_NAME VARCHAR(50),
    M_NAME VARCHAR(50),
    L_NAME VARCHAR(50),
    DOB DATE,
    GENDER VARCHAR(10),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    PIN_CODE VARCHAR(10)
);

CREATE TABLE USER_PHONE(
    USER_ID INT,
    PHONE_NO VARCHAR(15),
    PRIMARY KEY(USER_ID, PHONE_NO),
    FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE FLIGHT(
    FLIGHT_NO INT PRIMARY KEY,
    SOURCE VARCHAR(50),
    DESTINATION VARCHAR(50),
    DEP_TIME TIME,
    ARR_TIME TIME,
    AIRLINE_ID INT,
    FOREIGN KEY (AIRLINE_ID) REFERENCES AIRLINE(AIRLINE_ID)
);

CREATE TABLE CLASS(
    CLASS_ID INT PRIMARY KEY,
    CLASS_TYPE VARCHAR(30),
    FARE DECIMAL(10,2)
);

CREATE TABLE TICKET(
    PNR_NO INT PRIMARY KEY,
    USER_ID INT,
    FLIGHT_NO INT,
    CLASS_ID INT,
    SEAT_NO VARCHAR(10),
    DATE_TIME DATETIME,
    STATUS VARCHAR(20),
    FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID),
    FOREIGN KEY(FLIGHT_NO) REFERENCES FLIGHT(FLIGHT_NO),
    FOREIGN KEY(CLASS_ID) REFERENCES CLASS(CLASS_ID)
);

CREATE TABLE PAYMENT(
    TRANSACTION_ID INT PRIMARY KEY,
    PNR_NO INT,
    PAYMENT_MODE VARCHAR(30),
    AMOUNT DECIMAL(10,2),
    FOREIGN KEY(PNR_NO) REFERENCES TICKET(PNR_NO)
);
